production:
  db:
    name: ali24_prod
    hosts:
      - 127.0.0.1:27017
    options:
  admin_credentials: admin:lekdUkd_4UU2

development:
  db:
    name: ali24_dev
    hosts:
      - 127.0.0.1:27017
    options:
  admin_credentials: admin:admin

test:
  db:
    name: ali24_test
    hosts:
      - 127.0.0.1:27017
    options:
  admin_credentials: admin:admin
