production:
  db:
    name: apiwholesale_prod
    hosts:
      - localhost:27017
    options:
  admin_credentials: admin:admin

development:
  db:
    name: apiwholesale_dev
    hosts:
      - localhost:27017
    options:
  admin_credentials: admin:admin

test:
  db:
    name: apiwholesale_test
    hosts:
      - localhost:27017
    options:
  admin_credentials: admin:admin
